# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9187c18956ebf3d95d4f66d279690f419e35cf62d0954d0aec6e9c14b00e0b0ea0122bcf6694a7671994004d002f796c4fc6e8f3b757f89a0743be7ba04a3623

test:
  secret_key_base: 593bd1aafe4493d5a76d580c2db1f63b6122c23dee7412035fd4e5b796e0ac485964399152bb298abce99a262c99cc6c0d3cd452b9e7d94b7c6132014e55702c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
